[tools]
node = "lts"
"npm:@trunkio/launcher" = "1.3.4"

[tasks.install]
run = "bash scripts/install.sh"

[tasks.lint]
run = "trunk check -v"

[tasks.fmt]
run = "trunk fmt"

[tasks.test]
run = "ls fdroid/repo/index.xml"

[tasks.codegen]
run = "echo 'No codegen available'"

[tasks.ci]
depends = ["lint", "test"]
